# .goreleaser.yaml
version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: dirfuzz
    binary: dirfuzz
    main: ./cmd/dirfuzz
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

  - id: dirfuzz-mcp
    binary: dirfuzz-mcp
    main: ./cmd/mcp
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

  - id: dirfuzz-monitor
    binary: dirfuzz-monitor
    main: ./cmd/monitor
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
